### ISSUE TITLE
puzzle game

### ISSUE THREAD

**Issue by NaMiKA0305** [edm00se/awesome-board-games#271]
### Expected Behavior
it is a puzzle game where we have to click on different tiles . if we find both of them similar than we will get 1 point.

### Screenshots
![Screenshot (105)](https://github.com/edm00se/awesome-board-games/assets/98265007/1466570b-4994-4803-beb0-5fc68ad58eab)

**Comment by edm00se** [comment]
Please read the entirety of #269. Thank you.
