### ISSUE TITLE
add url for buying the game

### ISSUE THREAD

**Issue by stevemao** [edm00se/awesome-board-games#39]
### Expected Behavior

An easy way to tell people where to buy the game

**Comment by edm00se** [comment]
The intention of an [awesome list](https://github.com/sindresorhus/awesome/blob/master/awesome.md) is to focus on awesome things. While I think some people might find it useful to have a link to purchase, should they be interested, it is problematic as I've no intention of opening that can of worms.

It's problematic in that:
1. it could show favoritism
2. opens the potential for referral links, and this is an open source project which I expect nothing back from, other than aiding fellow lovers of board games
3. is likely unnecessary, considering that we live in an age of quality search engines and online vendors

This last point, \#3, is the most persuasive in my opinion. There may come a day this changes, but for now I'm going to treat it as not something this repo pursues.
