### ISSUE TITLE
Quiz APP 

### ISSUE THREAD

**Issue by AnshMeshram** [edm00se/awesome-board-games#422]
Hi there,
I want to add the quiz app using HTML CSS  JS 
please accept my issue

**Comment by edm00se** [comment]
This is not an acceptable contribution for this repo. You need to read and understand both [the contributing guide](https://github.com/edm00se/awesome-board-games/blob/main/contributing.md) and the welcome issue, #269. Please do not attempt to submit anything further until you have read and understood both of those things.
