### ISSUE TITLE
Happy Hacktoberfest 2019!

### ISSUE THREAD

**Issue by edm00se** [edm00se/awesome-board-games#55]
# Add Your Favorite Board Game

If you're looking to contribute for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) and would love an "easy win", but don't want to make it to a superfluous repository, then please consider this one and contribute by adding a favorite board game to this list. There's no need to create an issue.

## What Is This?

This is [an awesome list](https://github.com/sindresorhus/awesome/blob/master/awesome.md) which lets people show their love for, and recommend, board games.

## How Do I Contribute?

Please read the [contributing guide](https://github.com/edm00se/awesome-board-games/blob/master/contributing.md), it's a quick read, and follow the [formatting guide](https://github.com/edm00se/awesome-board-games/blob/master/formatting.md), again it's short and includes examples.

Please tag your PRs with this issue \# if you're contributing during October for [Hacktoberfest](https://hacktoberfest.digitalocean.com/). I'll close this issue after the end of October. For now, happy contributing!

**Comment by deadcoder0904** [comment]
Hey @edm00se I've submitted a PR at awesome #1621

**Comment by edm00se** [comment]
Thanks for the interest. As it happens, it already is added to the main awesome repo.

This issue is meant to be a landing point for others to contribute content to this list.

**Comment by edm00se** [comment]
> This issue is meant to be a landing point for others to contribute content to this list.

**Comment by deadcoder0904** [comment]
Ohh gotcha now. I misinterpreted poorly haha.

**Comment by edm00se** [comment]
No worries here. I've updated the issue description to hopefully prevent anyone else from reading it similarly.

**Comment by edm00se** [comment]
Thank you to all who participated!

This repo is still very much open for contribution.
