### ISSUE TITLE
Pull Request Failed

### ISSUE THREAD

**Issue by Quinncuatro** [edm00se/awesome-board-games#74]
### Expected Behavior

I was hoping for a straight `.md` edit to merge cleanly.

### Actual Behavior

It looks like the three current pull requests failed on the same "Node Code Formatter" test.

### Steps to Reproduce

Add a board game and try to open a PR.

### Screenshots

![Screen Shot 2019-10-01 at 1 33 02 PM](https://user-images.githubusercontent.com/5264878/65985560-10177480-e450-11e9-945f-7810d19ffa91.png)

**Comment by edm00se** [comment]
I am aware of this and it's being looked into. When I review your PR it won't hold it up.

**Comment by Quinncuatro** [comment]
No worries. Let me know if you need me to do anything once you're all set.

**Comment by edm00se** [comment]
The GitHub Action responsible has been pulled for now.
